In [87]:
import os, sys
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.font_manager as font_manager

def lfsr_crc8_1step(bit_in, seed):
    reg0 = np.concatenate((bit_in^seed[7], bit_in^seed[7]^seed[0]),axis=None)
    reg1 = np.concatenate((bit_in^seed[7]^seed[1], bit_in^seed[7]^seed[2]),axis=None)
    reg2 = np.concatenate((seed[3], bit_in^seed[7]^seed[4]),axis=None)
    reg3 = np.concatenate((seed[5], seed[6]),axis=None)
    reg01 = np.concatenate((reg0, reg1),axis=None)
    reg23 = np.concatenate((reg2, reg3),axis=None)
    reg0123 = np.concatenate((reg01, reg23),axis=None)
    seed = reg0123
    
        
    return seed

def lfsr_crc8_1step_a(bit_in, seed):
    reg0 = np.concatenate((bit_in^seed[7], seed[0]^seed[7]),axis=None)
    reg1 = np.concatenate((seed[7]^seed[1], seed[7]^seed[2]),axis=None)
    reg2 = np.concatenate((seed[3], seed[7]^seed[4]),axis=None)
    reg3 = np.concatenate((seed[5], seed[6]),axis=None)
    reg01 = np.concatenate((reg0, reg1),axis=None)
    reg23 = np.concatenate((reg2, reg3),axis=None)
    reg0123 = np.concatenate((reg01, reg23),axis=None)
    seed = reg0123
    
        
    return seed

In [95]:
a=1^0
print(a)

b=np.ones(3)
print(b)

print(np.concatenate(([1,2],[2,3],[3,4]),axis=None))

# seed = np.array([1,1,1,1,1,1,1,1])
seed = np.array([0,0,0,0,0,0,0,0])
print(seed)
print(seed[5:6])

reg_new = lfsr_crc8_1step(1, seed)
print(reg_new)


################## transmitter ####################
# message = np.array([1,1,0,1,1,1,1,0])
message = np.array([1,1,0,0,1,0,1,1,1,1,1,1,0,1])
initial_crc = np.array([0,0,0,0,0,0,0,0])
message_ext0 = np.concatenate((initial_crc, message),axis=None)

m_len = len(message_ext0)
seed = np.array([0,0,0,0,0,0,0,0])
for i in range(m_len):
    checksum = lfsr_crc8_1step_a(message_ext0[m_len-i-1], seed)
    seed = checksum

print('transimitter checksum is',checksum)

############ receiver #################
message_ext1 = np.concatenate((checksum, message),axis=None)
print('message_ext1: ',message_ext1)
m_len = len(message_ext1)
seed = np.array([0,0,0,0,0,0,0,0])
for i in range(m_len):
    checksum = lfsr_crc8_1step_a(message_ext1[m_len-i-1], seed)
    seed = checksum

print('receiver checksum is ',checksum)

1
[1. 1. 1.]
[1 2 2 3 3 4]
[0 0 0 0 0 0 0 0]
[0]
[1 1 1 1 0 1 0 0]
transimitter checksum is [0 0 1 0 1 0 1 1]
message_ext1:  [0 0 1 0 1 0 1 1 1 1 0 0 1 0 1 1 1 1 1 1 0 1]
receiver checksum is  [0 0 0 0 0 0 0 0]
